### ISSUE TITLE
jOOQの導入確認について

### ISSUE THREAD

**Issue by KonoLevel1** [KonoLevel1/spring-boot-practice#1]
jOOQの導入方法が正しいのか

**Comment by KonoLevel1** [comment]
https://github.com/KonoLevel1/spring-boot-practice/blob/master/bbs/bbs-test/build.gradle

```
dependencies {
	省略
	// jooq導入
	implementation 'org.springframework.boot:spring-boot-starter-jooq'
	省略
	}
```

**Comment by KonoLevel1** [comment]
@kanecro 

jOOQについて、Mavenの導入記事は大量に見かけたものの、
Gradleについては少なく、それぞれ別の書き方であったため、
https://start.spring.io/　
を利用して、build.gradleの生成を行いましたが、
正しいかどうか不安なため確認をお願いできればと思います。

**Comment by KonoLevel1** [comment]
jOOQ公式の下記のページを実施していたところ、エラーが発生した。
https://www.jooq.org/doc/3.13/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/

実行
```
koyamajunichi@MacBook-Pro bbstest % java -classpath jooq-3.13.3.jar:\
jooq-meta-3.13.3.jar:\
jooq-codegen-3.13.3.jar:\
reactive-streams-1.0.2.jar:\
mysql-connector-java-5.1.18-bin.jar:. \
org.jooq.codegen.GenerationTool library.xml

```
結果
```
エラー: メイン・クラスorg.jooq.codegen.GenerationToolを初期化できません
原因: java.lang.NoClassDefFoundError: org/jooq/util/jaxb/tools/XMLAppendable
```

- jooq-3.13.3.jar
- jooq-meta-3.13.3.jar
- jooq-codegen-3.13.3.jar

上記３つをダウンロードし、再度実行したところエラー内容が変わった。


実行
```
koyamajunichi@MacBook-Pro bbstest % java -classpath jooq-3.13.3.jar:\
jooq-meta-3.13.3.jar:\
jooq-codegen-3.13.3.jar:\
reactive-streams-1.0.2.jar:\
mysql-connector-java-5.1.18-bin.jar:. \
org.jooq.codegen.GenerationTool library.xml
```
結果

```
7月 28, 2020 10:44:08 午前 org.jooq.tools.JooqLogger info
情報: Initialising properties  : library.xml
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at org.jooq.util.jaxb.tools.MiniJAXB.getNamespace(MiniJAXB.java:393)
	at org.jooq.util.jaxb.tools.MiniJAXB.addDefaultNamespace(MiniJAXB.java:186)
	at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:173)
	at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:159)
	at org.jooq.codegen.GenerationTool.load(GenerationTool.java:1024)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
```

**Comment by KonoLevel1** [comment]
https://www.jooq.org/doc/latest/manual/code-generation/

**Comment by KonoLevel1** [comment]
> Gradleならではの設定方法

https://github.com/etiennestuder/gradle-jooq-plugin

**Comment by KonoLevel1** [comment]
https://github.com/etiennestuder/gradle-jooq-plugin
MySQLデータベーススキーマからjOOQを利用して、Javaソースを作成する。

生成されるべき場所（デフォルト設定）
build/generated-src/jooq/

**Comment by KonoLevel1** [comment]
generateBbs_testJooqSchemaSource - Generates the jOOQ sources from the 'bbs_test' jOOQ configuration.

`gradle generateBbs_testJooqSchemaSource`

```
> Task :generateBbs_testJooqSchemaSource FAILED
7月 29, 2020 8:42:47 午前 org.jooq.tools.JooqLogger info
情報: Initialising properties  : /Users/koyamajunichi/Documents/spring-boot-practice/bbs/bbs-test/build/tmp/generateBbs_testJooqSchemaSource/config.xml
7月 29, 2020 8:42:48 午前 org.jooq.tools.JooqLogger error
重大: Cannot read /Users/koyamajunichi/Documents/spring-boot-practice/bbs/bbs-test/build/tmp/generateBbs_testJooqSchemaSource/config.xml. Error : com.mysql.jdbc.Driver
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.jooq.codegen.GenerationTool.loadClass0(GenerationTool.java:977)
        at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:921)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:346)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateBbs_testJooqSchemaSource'.
> Process 'command '/usr/local/Cellar/openjdk/14.0.1/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
1 actionable task: 1 executed
```

**java.lang.ClassNotFoundException: com.mysql.jdbc.Driver**

JDBCドライバにクラスパスが設定されていないか誤っている。

参考にしたページ

- https://stackoverflow.com/questions/1585811/classnotfoundexception-com-mysql-jdbc-driver
- https://www.it-swarm-ja.tech/ja/intellij-idea/intellij-idea%E3%81%AB%E5%A4%96%E9%83%A8%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95%E3%81%AF%EF%BC%9F/940262834/

- https://github.com/etiennestuder/gradle-jooq-plugin/issues/103

- https://living-sun.com/ja/mysql/570664-grails-classnotfoundexception-commysqljdbcdriver-in-war-deployment-mysql-tomcat-grails-gradle.html

### エラーの原因となるもの

- JDBCドライバにクラスパスが設定されていないか誤っている。
- MySQLのユーザーとパスワードが間違っている

**Comment by kanecro** [comment]
@KonoLevel1 
https://github.com/etiennestuder/gradle-jooq-plugin#defining-your-database-drivers
https://stackoverflow.com/questions/40446825/classnotfoundexception-in-buildscript-when-using-the-mysql-connector

**Comment by kanecro** [comment]
ググりワード
`Gradle jOOQ  java.lang.ClassNotFoundException: com.mysql.jdbc.Driver`
1分で解決

**Comment by KonoLevel1** [comment]
dependenciesに下記を追加
`jooqRuntime "mysql:mysql-connector-java:8.0.15"`

コマンド実行
`gradle generateSampleJooqSchemaSource`

エラー発生
```
> Task :generateSampleJooqSchemaSource FAILED
7月 29, 2020 11:31:26 午前 org.jooq.tools.JooqLogger info
情報: Initialising properties  : /Users/koyamajunichi/Documents/spring-boot-practice/bbs/bbs-test/build/tmp/generateSampleJooqSchemaSource/config.xml
7月 29, 2020 11:31:27 午前 org.jooq.tools.JooqLogger error
重大: Cannot read /Users/koyamajunichi/Documents/spring-boot-practice/bbs/bbs-test/build/tmp/generateSampleJooqSchemaSource/config.xml. Error : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:354)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
        ... 7 more
Caused by: java.net.UnknownHostException: ${MYSQL_HOST:localhost}: nodename nor servname provided, or not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1505)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1354)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1288)
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:132)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
        ... 10 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateSampleJooqSchemaSource'.
> Process 'command '/usr/local/Cellar/openjdk/14.0.1/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```
調査中

**Comment by KonoLevel1** [comment]
Communications link failureが発生する問題解消

原因
build.gradleのurlが原因で接続できていなかった。

変更前
`url = 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/bbs_test?serverTimezone=JST' `
変更後
`url = 'jdbc:mysql://localhost:3306/bbs_test?serverTimezone=JST' `
